# Generated by Django 5.0.2 on 2026-03-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_is_paid_course_is_free_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='paid',
            new_name='is_active',
        ),
    ]
