# Generated by Django 5.0.2 on 2026-03-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_options_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='Todos os níveis', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
